services:
  postgres:
    image: postgres:15-alpine
    container_name: pipelinex_postgres
    environment:
      POSTGRES_USER: pipelinex
      POSTGRES_PASSWORD: pipelinex
      POSTGRES_DB: pipelinex
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/pipelinex/persistence/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pipelinex -d pipelinex"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
